# ---------------------------------------------------------------------------- #
#                                                                              #
#                   B e a m T o o l A c t i o n s . p r o p e r t i e s        #
#                                                                              #
# ---------------------------------------------------------------------------- #

# This file gathers resources to be injected in the BeamToolActions class.
#
# This is the generic (english) version

openBeamPatterns.Action.text = Beam patterns...
openBeamPatterns.Action.shortDescription = Open the beam patterns tool palette
